; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+08 on Mon Nov 15 2021 23:44:05 GMT+0300 (Москва, стандартное время)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


