; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+08 on Mon Nov 15 2021 23:44:07 GMT+0300 (Москва, стандартное время)
G91              ; relative positioning
G1 H1 Z340 F4000 ; move Z up until the endstop is triggered
G1 Z-5 F360      ; go back a few mm
G1 H1 Z10 F360   ; move slowly to Z axis endstop once more (second pass)
G90              ; absolute positioning
G92 Z330.15	     ; set Z position to axis maximum (you may want to adjust this)