; sleep.g
; called when M1 (Sleep) is being processed
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+08 on Mon Nov 15 2021 23:44:07 GMT+0300 (Москва, стандартное время)
M107 ;fans off
M109 R150 ;wait for cool
M568 P0:1 S0 A0 ;off heaters 0 and 1

M81 ;power off