; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+08 on Mon Nov 15 2021 23:44:08 GMT+0300 (Москва, стандартное время)

M568 P0:1 S0 A0 ;off heaters 0 and 1
M107 ;fans off
