; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+08 on Mon Nov 15 2021 23:44:08 GMT+0300 (Москва, стандартное время)
; Wait for set temperatures to be reached
M116 P1

